### ISSUE TITLE
iOS/iPadOS Support

### ISSUE THREAD

**Issue by soko1** [triumphantomato/cryptsidian#1]
Hello! 

Are there any plans to support the plugin for iOS/iPadOS? Such a plugin is very lacking :(

Thanks!

![image](https://user-images.githubusercontent.com/1101972/141660348-4c289fdc-9269-45ee-b1e4-33aaeca8ecea.png)

**Comment by triumphantomato** [comment]
hi @soko1  - right now there are no plans for mobile support on either iOS or Android.

i'd like to bring support for this to mobile in the future, but it is a major rewrite, which essentially involves rewriting the entire plugin.

In chatting with the Obsidian maintainers, I'm told that file descriptor based API access like on POSIX-like systems via `node` is not supported for mobile with Obsidian, so i need to rewrite to use Obsidian's `TFile` API method and possibly switch the crypto API as well. This means rewriting every function that currently touches a file (most of them) and their tests (almost all tests).

Until i have the time to dedicate to that i won't be able to provide mobile support! Thank you for understanding.
