### ISSUE TITLE
Empty files after decryption

### ISSUE THREAD

**Issue by pplanel** [triumphantomato/cryptsidian#11]
As the title says, encrypted my vault, when decrypting, files were truncated.

**Comment by triumphantomato** [comment]
Hi Pedro, were the files empty or truncated?

Did you follow the guidelines in the readme?

The files are not truncated when decrypting: [this unit test at L178](https://github.com/triumphantomato/cryptsidian/blob/d7071cd4666a0ab1ffd0ec6b69a75a78a9e2cab5/test/cryptsidian_tests.mjs#L178) tests for it
