### ISSUE TITLE
Couple questions.

### ISSUE THREAD

**Issue by allegedly-marcus** [triumphantomato/cryptsidian#13]
does this make that if i use any type of sync method the others devices will see the encrypted data only? what about repos? and what about in traffic, is it still encrypted?

If so, i would like to use it with github with obsidian git, do you reckon that should/could work?

What about using this with other plugins like excalidraw? the excalidraw would still be encrypted and it would work? (i guess that it is because is still on the document in markdown format)

Once i decrypt my vault, where is the decrypted vault stored, if its not, how is it displayed then?(searching for vulnerabilities)

If im working on my decrypted vault and obsidian doesn't close properly, after saving my files as with control + S, my decrypted "saved" data is stored and safe? it brokes? what about if my pc suddenly turns off?(after saving)

**Comment by allegedly-marcus** [comment]
Those are the questions, Thank you before hand.

**Comment by triumphantomato** [comment]
hello, thank you for your questions - this plugin encrypts and decrypts the
files in place. this means when you encrypt or decrypt the vault the files
are overwritten in place. "in place" means where they are currently stored,
so if your vault looks like /yourvault/file1.md, /yourvault/file2.md, ... ,
/yourvault/file_n.md, then each of those files will be encrypted and stored
as /yourvault/file1.md, /yourvault/file2.md, ... , /yourvault/file_n.md.
when you decrypt they will be decrypted and again stored as
/yourvault/file1.md, /yourvault/file2.md, ... , /yourvault/file_n.md.

i have not tested cryptsidian with other plugins like obsidian git or
excalidraw, so cannot comment on the compatibility. from obsidian git
README it looks like that plugin does an "Automatic vault backup every X
minutes" - so whatever state the vault is in (encrypted or decrypted)
during that automatic backup is what will get pushed to git

personally i have used cryptsidian with Dropbox and it has worked for my
setup (one computer no mobile use of obsidian), but i have not tested this
extensively

if you decide to try cryptsidian with another plugin please share your
results! thank you
