### ISSUE TITLE
Workflow for decrypting files

### ISSUE THREAD

**Issue by mroberts1** [triumphantomato/cryptsidian#14]
Hi, I installed the plugin and set up the Encrypt and Decrypt modals with the same password.

However, when I close and reopen the vault, the test file that I encrypted in there is not accessible and it isn't clear how to enter the password to decrypt it. Cmd-P simply gives the Encrypt/Decrypt modals from the original setup.

How do I decrypt files that I've encrypted using this plugin? Where do I enter the password?

**Comment by triumphantomato** [comment]
hi, thanks for your question. this plugin encrypts and decrypts *the entire vault* at once. so when you enter a password into the encrypt modal, you are encrypting your entire vault. when you enter a password into the decrypt modal, you are decrypting the entire vault. please see the README for more, thanks. if you're still having trouble please feel free to re-open this issue.
