### ISSUE TITLE
Encryption / Decryption - attachments-pasted Images.

### ISSUE THREAD

**Issue by ForxEf** [triumphantomato/cryptsidian#15]
Running encryption and then decryption or just encryption or decryption render any pasted images as corrupt files.  Can these be treated independently. Is is possible to support a separate decryption mechanism to handle these?

**Comment by triumphantomato** [comment]
hi ForxEf, thank you for the report. could you share a sample file (you can upload it to dropbox or other sharing service and paste a share link here) so I can test it?

please also share some info so i can debug -
1. operating system
2. version of cryptsidian
3. version of obsidian
4. file format of the pasted image
5. file format of the document the image is being pasted into (this is probably `.md`) 

thanks
