### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by sk365** [triumphantomato/cryptsidian#3]
Hi, 
would it be possible to make the extension work under Android?
Best, 
Stefan

**Comment by triumphantomato** [comment]
Hi Stefan,

I'd love to, but the work involved requires a full rewrite of the extension. Currently I don't have time for this. Please see https://github.com/triumphantomato/cryptsidian/issues/1 for the technical details.

Thanks!

**Comment by sk365** [comment]
Find a workaround here: 
https://github.com/sk365/ObsidianEncryptedCloudSync
