### ISSUE TITLE
Accidentally corrupted files by opening them outside of obsidian.

### ISSUE THREAD

**Issue by psython123** [triumphantomato/cryptsidian#6]
Is there any way to recover the corrupted files?

**Comment by triumphantomato** [comment]
Hi i'm sorry to hear this.

Do you have a backup of these files before you encrypted them? That would
be the best way to recover them.

Your other option is if you have a backup of the files immediately after
you encrypted them, but before you opened them in another application. In
that case, you may still be able to recover them by decrypting with
Cryptsidian.

Wishing you the best

**Comment by psython123** [comment]
Hey, thanks for your fast reply.

Unfortunately, I didn't do a backup before. Thankfully though, the files weren't extremely important. I know better next time.

By the way, I have a question: What happens if you try to decrypt with a wrong password?

**Comment by triumphantomato** [comment]
From the readme:

"If you use different passwords for encryption and decryption, your files will become corrupted."
