### ISSUE TITLE
not able to decrypt any files

### ISSUE THREAD

**Issue by 0xConcordance** [triumphantomato/cryptsidian#8]
Am not able to decrypt any files. I have tried to decrypt multiple times now - with one different variation of the password so the files might be corrupted now.

I am not entirely sure what the issue is though. Pretty sure the password matches the encryption password. Any way I can troubleshoot this? Using windows 10.

**Comment by 0xConcordance** [comment]
Just to elaborate on what I did that led to this issue: 

Encrypted Files with password -> Opened "test file" to see if it worked (it had) -> tried to decrypt it with the password (didn't work) -> tried multiple times

**Comment by triumphantomato** [comment]
Thanks for the additional detail. Unfortunately I suspect the answer is "no", at least for the file you opened ("test" file) [1].

Do you have a backup?

From the readme, first warning:
> Backup the Vault - before running the plugin make a backup to save your data.

If you do, the easiest thing is to restore from the backup.

If you do not, you may be able to recover the other files if and only if:
0/ They were never opened (and thus are not corrupted)
1/ You know exactly how many times you tried to decrypt
2/ You know exactly the passwords used each time you decrypted
3/ You know exactly the password used when you initially encrypted

In this case, you could manually edit the code to run the "encrypt" command with the same passwords from (2) mapping exactly and in-order to (1), and then run a final decrypt command with the same password as (3). 

[1] Please see this note from the top of the readme:

> Do not open files in Obsidian.md (or other app) after encrypting them. Contents can become corrupted and irrecoverable. The plugin auto-closes all open notes to avoid accidental corruption

Encryption is a very low-level operation (you are dealing directly with bytes on disk). Obsidian doesn't know which files are encrypted or not, so it expects any file it opens to be a normal (unencrypted) file. My suspicion is that it then does some things - maybe changes metadata or the like - that changes the file. 

These changes are fine for normal files, but corrupt encrypted files (encrypted files must maintain the exact same byte representation to be decrypted successfully).

I explored a few solutions to this but couldn't find one that made sense - please see past closed issues if you are interested. Regrettably, none of them are helpful for recovering your file. Hopefully you made a backup!

**Comment by 0xConcordance** [comment]
Luckily I have a backup of the data so nothing important is lost.
